name = "cladhunter"
main = "cloudflare/worker.ts"
compatibility_date = "2024-10-01"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "data_cladhunter"
database_id = "ca08f9d1-440e-4673-8b43-dd6514fe8bef"
