name = "cladhunter-api"
main = "cloudflare/worker.ts"
compatibility_date = "2024-10-01"
node_compat = true

[[d1_databases]]
binding = "DB"
database_name = "cladhunter"
database_id = "00000000-0000-0000-0000-000000000000" # replace with your real database id
