/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_0f597298 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/dvvaevudbrrxynpgaguz/database/tables

export { del, get, getByPrefix, mdel, mget, mset, set } from "../_shared/kv-store.ts";
