/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dvvaevudbrrxynpgaguz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2dmFldnVkYnJyeHlucGdhZ3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExNzEyNjMsImV4cCI6MjA3Njc0NzI2M30.rP-s3C-EQLQ7AfgMLKw2Jw8fEmkQ8sWyZkAKwn1QNIs"
