/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tznywaptvjivzooekkiq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6bnl3YXB0dmppdnpvb2Vra2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMzc5NjksImV4cCI6MjA3NjkxMzk2OX0.CMJg4gtCy6vayGmqc76KTJRSx-5PucBr8E0nnPzgPZw"
